version: "3"
services:
  chat-service-db:
    container_name: chat-service-db
    image: mysql
    ports:
      - "7200:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - default

  users-service-db:
    container_name: users-service-db
    image: mysql
    ports:
      - "7201:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - default