version: "3"
services:
  chat-service-db:
    container_name: chat-service-db
    image: mysql
    ports:
      - "7200:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - default

  users-service-db:
    container_name: users-service-db
    image: mysql
    ports:
      - "7201:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - default
      
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 7300:80
    depends_on:
      - "chat-service-db"
      - "users-service-db"
    links:
      - users-service-db
      - chat-service-db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
