version: "3"
services:
  chat-service-db:
    container_name: chat-service-db
    image: mysql
    ports:
      - "7200:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - default

  users-service-db:
    container_name: users-service-db
    image: mysql
    ports:
      - "7201:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - default

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 7300:80
    depends_on:
      - "chat-service-db"
      - "users-service-db"
    links:
      - users-service-db
      - chat-service-db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

  chat-service:
    build: ./chat-service/
    container_name: "chat-service"
    environment:
      USERS_SERVICE_DB_URL: mysql://root:password@chat-service-db/db
      USER_SESSION_EXPIRY_HOURS: 1
    ports:
      - "7100:7100"
    depends_on:
      - "chat-service-db"
    links:
      - chat-service-db
    volumes:
      - ./chat-service:/usr/src/chat-service
    networks:
      - default

  users-service:
    build: ./users-service/
    container_name: "users-service"
    environment:
      USERS_SERVICE_DB_URL: mysql://root:password@users-service-db/db
      USER_SESSION_EXPIRY_HOURS: 1
    ports:
      - "7101:7101"
    depends_on:
      - "users-service-db"
    links:
      - users-service-db
    volumes:
      - ./users-service:/usr/src/users-service
    networks:
      - default

  api-gateway:
    build: ./api-gateway/
    container_name: "api-gateway"
    ports:
      - "7000:7000"
    depends_on:
      - "users-service"
      - "chat-service"
    links:
      - users-service
      - chat-service
    volumes:
      - ./api-gateway:/usr/src/api-gateway
    networks:
      - default

  chat-app:
    build: ./chat-app/
    container_name: "chat-app"
    ports:
      - "7001:7001"
    depends_on:
      - "api-gateway"
    links:
      - api-gateway
    volumes:
      - ./chat-app:/usr/src/chat-app
    networks:
      - default